id: config_optimization
name: Configuration Optimization Review
description: Review configuration for optimization opportunities and best practices
category: configuration

prompt: |
  Review Kafka configuration for optimization opportunities and best practices.
  
  Configuration Files:
  {config}
  
  Admin/Broker Info:
  {admin}
  
  Analyze configuration in these categories:
  
  1. PERFORMANCE TUNING:
     - num.network.threads (default 8, optimal?)
     - num.io.threads (default 8, optimal?)
     - socket.send.buffer.bytes
     - socket.receive.buffer.bytes
     - socket.request.max.bytes
     - num.replica.fetchers
     - replica.fetch.max.bytes
     - message.max.bytes
  
  2. DURABILITY SETTINGS:
     - min.insync.replicas
     - unclean.leader.election.enable (should be false)
     - default.replication.factor
     - acks configuration
  
  3. RETENTION & CLEANUP:
     - log.retention.hours/ms/bytes
     - log.segment.bytes
     - log.cleanup.policy (delete vs compact)
     - compression.type
     - log.cleaner settings
  
  4. MEMORY & JVM:
     - Heap size (-Xmx, -Xms)
     - Are they equal? (they should be)
     - GC algorithm (G1GC recommended)
     - JVM flags optimization
  
  5. REPLICATION SETTINGS:
     - replica.lag.time.max.ms
     - replica.fetch.min.bytes
     - replica.fetch.wait.max.ms
     - num.replica.fetchers
  
  6. CLIENT INTERACTION:
     - max.connections
     - max.connections.per.ip
     - request.timeout.ms
     - connections.max.idle.ms
  
  7. ZOOKEEPER/KRAFT:
     - zookeeper.session.timeout.ms
     - zookeeper.connection.timeout.ms
     - KRaft mode settings if applicable
  
  8. MONITORING & METRICS:
     - JMX settings
     - Metrics reporters
     - Log levels
  
  For each setting, provide:
  - Current value
  - Recommended value
  - Reason for change
  - Expected benefit
  - Risk level of change
  
  Common misconfigurations to check:
  - Heap too small/large
  - Replication settings too aggressive/loose
  - Retention too long for disk space
  - Network buffers too small
  - Thread pools undersized
  - Missing compression
  - Unclean leader election enabled
  - No min.insync.replicas
  
  Format as JSON:
  {
    "findings": [{
      "title": "Configuration optimization: [specific area]",
      "severity": "medium",
      "description": "Detailed configuration analysis",
      "current_config": {
        "setting_name": "current_value"
      },
      "recommendations": [
        {
          "setting": "num.network.threads",
          "current": "3",
          "recommended": "8",
          "reason": "Low value causing network bottleneck",
          "benefit": "2-3x network throughput improvement",
          "risk": "low"
        }
      ],
      "impact": "Current configuration limiting performance by ~50%",
      "remediation": "Apply recommended settings with rolling restart"
    }]
  }

severity_keywords:
  "critical misconfiguration": "high"
  "security risk": "high"
  "data loss risk": "critical"
  "performance impact": "medium"
  "suboptimal": "low"
  "best practice violation": "medium"

default_severity: medium
enabled: true
