# Site settings
title: KafkaPilot
description: >-
  CLI-first Kafka health diagnostics tool for production environments.
  Automatically collects cluster signals, identifies issues, and provides 
  actionable remediation guidance.

url: "https://softwaremill.github.io"
baseurl: "/kafkapilot"
version: "1.0.0"

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Author info
author:
  name: SoftwareMill
  email: hello@softwaremill.com

# Social links
github_username: softwaremill
email: hello@softwaremill.com

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Collections and defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.md"
    values:
      layout: "home"

# SEO
lang: en_US
timezone: UTC

# Custom variables
softwaremill:
  url: https://softwaremill.com
  text: SoftwareMill

# Navigation structure (used by sidebar)
navigation:
  getting_started:
    - title: "Overview"
      url: "/"
    - title: "Quickstart"
      url: "/quickstart"
    - title: "Installation"
      url: "/installation"
    - title: "Support"
      url: "/support"
  
  tutorials:
    - title: "All Tutorials"
      url: "/tutorials"
  
  reference:
    - title: "CLI Reference"
      url: "/api"
    - title: "Examples"
      url: "/examples"
    - title: "How-To Guides"
      url: "/how-to"