# Site settings
title: KafkaPilot
description: >-
  CLI-first Kafka health diagnostics tool for production environments.
  Automatically collects cluster signals, identifies issues, and provides 
  actionable remediation guidance.

url: "https://softwaremill.github.io"
baseurl: "/kafkapilot"

# Use GitHub Pages default theme
theme: minima

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation
header_pages:
  - quickstart.md
  - installation.md
  - tutorials.md
  - how-to.md
  - examples.md
  - api.md
  - support.md

# Author info
author:
  name: SoftwareMill
  email: hello@softwaremill.com

# Social links
github_username: softwaremill
email: hello@softwaremill.com

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# SEO
lang: en_US
timezone: UTC