name: Publish Crate

on:
  release:
    types: [created]
  workflow_dispatch: # This allows manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/index
          key: ${{ runner.os }}-cargo-index
          restore-keys: |
            ${{ runner.os }}-cargo-index

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build

      - name: Build the crate
        run: cargo build --release

#      - name: Publish to crates.io
#        env:
#          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
#        run: cargo publish --token $CARGO_REGISTRY_TOKEN --allow-dirty